# Clean up the directory structure
source: src/
destination: _build/

# Permalink setting
permalink: posts/:title/

# Pagination - this stuff changed a lot as of Jekyll 3.0.0
# paginate: 10
paginate_path: /posts/page:num/
gems: [jekyll-paginate]

# Exclude stuff
exclude: [README.md, node_modules, package.json, deploy-stage, deploy-prod, deploy-example, rsync_exclude.txt, scss]
keep_files: ['css/style.css']

# Adds scope for posts so you check "if is post"
defaults:
    -
        scope:
            path: ""      # empty string for all files
            type: posts   # limit to posts
        values:
            is_post: true # automatically set is_post=true for all posts

# Global site variables
title: Levi McGranahan
description: "I’m a designer living in Bloomington, Indiana. I work on web, print, and brand identity projects."
user: levimcg

# Custom collections
collections:
    projects:
        output: true
        permalink: /projects/:title/

highlighter: pygments
