title: Levi McGranahan
description: Web and brand identity
highlighter: pygments
sass:
    sass_dir: _sass
    style: expanded
permalink: notes/:title
paginate: 5
paginate_path: "/notes/page:num/"
exclude: [README.md, Rakefile, node_modules, Gruntfile.js, package.json, deploy-stage, deploy-prod]

user: levimcg

collections:
    projects:
        output: true

# This will be the default baseurl for development.
# Make a separate config file for production build
# with live url and compressed css.
baseurl: http://stage.levimcg.com
